from pathlib import Path

def put(path,content):
 p=Path(path); p.parent.mkdir(parents=True,exist_ok=True); p.write_text(content)

put('app/providers/correction_evidence.py','''"""Normalize actual correction routing evidence for manifests and UI/audit consumers."""\nimport json\nfrom pathlib import Path\nfrom typing import Any\nGEMINI="gemini-3.7-flash"\n\ndef summarize_routing(job_dir: Path) -> dict[str, Any]:\n    path=job_dir/"correction-routing.json"\n    try: payload=json.loads(path.read_text())\n    except (FileNotFoundError,OSError,json.JSONDecodeError):\n        return {"correction_policy":"GEMINI_FIRST","correction_initial_provider":GEMINI,"correction_route":GEMINI,"correction_models_used":[GEMINI],"correction_segment_counts":{},"correction_routing_manifest":None}\n    initial=str(payload.get("initial_provider") or GEMINI); route=[initial]\n    switches=payload.get("provider_switches",[])\n    if isinstance(switches,list):\n        for switch in switches:\n            if isinstance(switch,dict):\n                target=str(switch.get("to") or "").strip()\n                if target and target!=route[-1]: route.append(target)\n    counts=payload.get("segment_counts",{}); counts=counts if isinstance(counts,dict) else {}\n    return {"correction_policy":str(payload.get("requested_policy") or "GEMINI_FIRST"),"correction_initial_provider":initial,"correction_route":" -> ".join(route),"correction_models_used":route,"correction_segment_counts":counts,"correction_routing_manifest":"correction-routing.json"}\n''')

put('app/providers/terminology_consistency.py','''"""Deterministic provider-independent terminology consistency audit; report-only."""\nimport json\nfrom pathlib import Path\nfrom typing import Any\n\ndef _load(path,default):\n    try:return json.loads(path.read_text())\n    except (FileNotFoundError,OSError,json.JSONDecodeError):return default\n\ndef build_report(job_dir:Path)->dict[str,Any]:\n    corrected=_load(job_dir/"subtitles-corrected.json",{}); glossary=_load(job_dir/"glossary"/"global-terms.json",{})\n    segments=corrected.get("segments",[]) if isinstance(corrected,dict) else []; terms=glossary.get("terms",[]) if isinstance(glossary,dict) else []\n    issues=[]\n    for term in terms if isinstance(terms,list) else []:\n        if not isinstance(term,dict):continue\n        canonical=str(term.get("canonical") or "").strip()\n        if not canonical:continue\n        forms=[canonical]\n        for raw in term.get("variants",[]):\n            value=str(raw).strip()\n            if value and value not in forms:forms.append(value)\n        observed={}\n        for form in forms:\n            ids=[str(seg.get("segment_id") or "") for seg in segments if isinstance(seg,dict) and form in str(seg.get("corrected_text") or seg.get("text") or "")]\n            if ids:observed[form]=ids\n        if len(observed)>1:\n            ids=[]\n            for values in observed.values():\n                for sid in values:\n                    if sid and sid not in ids:ids.append(sid)\n            issues.append({"canonical":canonical,"variants":list(observed),"occurrences":{k:len(v) for k,v in observed.items()},"segment_ids":ids,"confidence":str(term.get("confidence") or "low"),"suggested_action":"review"})\n    return {"schema_version":1,"mode":"report_only","provider_independent":True,"timestamps_modified":False,"segments_modified":False,"issue_count":len(issues),"issues":issues}\n\ndef run_terminology_consistency(job_dir:Path)->dict[str,Any]:\n    report=build_report(job_dir); path=job_dir/"terminology-consistency.json"; tmp=path.with_suffix(path.suffix+".tmp"); tmp.write_text(json.dumps(report,ensure_ascii=False,indent=2)+"\\n"); tmp.replace(path); return report\n''')

p=Path('app/providers/correction_runtime.py'); s=p.read_text()
def r(a,b):
 global s
 if a not in s: raise SystemExit('missing runtime pattern: '+a[:80])
 s=s.replace(a,b,1)
r('import json\nimport os\nimport threading\n','import csv\nimport hashlib\nimport json\nimport os\nimport threading\n')
r('from app.providers.minimax_quota import MiniMaxQuotaClient, MiniMaxQuotaSnapshot\n','from app.providers.minimax_quota import MiniMaxQuotaClient, MiniMaxQuotaSnapshot\nfrom app.providers.correction_evidence import summarize_routing\n')
start=s.index('def _empty_terms('); end=s.index('\ndef main() -> int:',start)
replacement='''def _m3_terms_generator(client: MiniMaxCorrectionClient, *, context: str):\n    def generate(raw_segments):\n        from app.providers import correct_text as base\n        source=[{"segment_id":x["segment_id"],"text":x["raw_text"]} for x in raw_segments]\n        sha=hashlib.sha256(json.dumps(source,ensure_ascii=False,separators=(",",":")).encode()).hexdigest(); out=base.JOB/"glossary"; out.mkdir(parents=True,exist_ok=True); cache=out/"global-terms.json"\n        try: cached=json.loads(cache.read_text()) if cache.exists() else None\n        except (OSError,json.JSONDecodeError): cached=None\n        if isinstance(cached,dict) and cached.get("provider")=="minimax" and cached.get("source_sha256")==sha: return cached.get("terms",[]) if isinstance(cached.get("terms",[]),list) else []\n        try:\n            record=client.extract_terms(raw_segments,context=context); terms=record.get("terms",[]) if isinstance(record.get("terms",[]),list) else []; record={**record,"source_sha256":sha,"cache_hit":False,"error_type":None,"safe_error":None}\n        except Exception as exc:\n            terms=[]; record={"provider":"minimax","model":os.getenv("MINIMAX_M3_MODEL","MiniMax-M3"),"prompt_version":"terminology-v1-minimax-m3","source_sha256":sha,"usage_metadata":{"request_count":0,"billing_mode":"token_plan"},"terms":[],"raw_response":None,"cache_hit":False,"error_type":type(exc).__name__,"safe_error":str(exc)[-500:]}\n        _atomic_json(cache,record)\n        with (out/"global-terms.csv").open("w",encoding="utf-8",newline="") as stream:\n            writer=csv.DictWriter(stream,fieldnames=["canonical","variants","confidence"]); writer.writeheader()\n            for term in terms:\n                if isinstance(term,dict): writer.writerow({"canonical":term.get("canonical",""),"variants":" | ".join(str(v) for v in term.get("variants",[])),"confidence":term.get("confidence","")})\n        return terms\n    return generate\n\n'''
s=s[:start]+replacement+s[end+1:]
r('        if runtime.decision.provider is CorrectionProvider.MINIMAX_M3:\n            base.generate_terms = _empty_terms\n','        if runtime.decision.provider is CorrectionProvider.MINIMAX_M3:\n            base.generate_terms = _m3_terms_generator(m3_client, context=runtime.context)\n')
old='''        routing = json.loads(\n            (base.JOB / "correction-routing.json").read_text(encoding="utf-8")\n        )\n        initial_provider = str(routing.get("initial_provider") or CorrectionProvider.GEMINI.value)\n        provider_route = (\n            "minimax-m3 -> gemini-3.7-flash"\n            if initial_provider == CorrectionProvider.MINIMAX_M3.value\n            else "gemini-3.7-flash"\n        )\n'''
if old not in s: raise SystemExit('missing route block')
s=s.replace(old,'        provider_route = str(summarize_routing(base.JOB)["correction_route"])\n',1)
p.write_text(s)

p=Path('app/providers/correct_text_hardened.py'); s=p.read_text()
old='''def main() -> int:\n    if os.getenv("MINIMAX_M3_ENABLED", "false").strip().lower() in {\n        "1", "true", "yes", "on"\n    }:\n        from app.providers import correction_runtime\n\n        return correction_runtime.main()\n    if correction_cascade_enabled():\n        return cascade.main()\n    # Keep the default path byte-for-byte compatible in behavior with the\n    # previously deployed hardened implementation.\n    legacy.generate_json = generate_json\n    return legacy.main()\n'''
new='''def _with_consistency(result: int) -> int:\n    if result == 0:\n        from app.providers.terminology_consistency import run_terminology_consistency\n        run_terminology_consistency(base.JOB)\n    return result\n\ndef main() -> int:\n    if os.getenv("MINIMAX_M3_ENABLED", "false").strip().lower() in {"1", "true", "yes", "on"}:\n        from app.providers import correction_runtime\n        return _with_consistency(correction_runtime.main())\n    if correction_cascade_enabled(): return _with_consistency(cascade.main())\n    legacy.generate_json = generate_json\n    return _with_consistency(legacy.main())\n'''
if old not in s: raise SystemExit('missing hardened main'); p.write_text(s.replace(old,new,1))
