"""Create deterministic exports for the formats selected by the user.

Internal JSON/CSV evidence is always retained for QA, observability and the
subtitle editor. User-facing sidecars are created only when requested. DOCX and
PDF are intentionally not generated by this pipeline.
"""
from __future__ import annotations

import csv
import hashlib
import json
import os

from docx import Document
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.cidfonts import UnicodeCIDFont
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from pathlib import Path
from typing import Any

from app.jobs.exports import normalize_output_formats

DATA_DIR = Path(os.environ.get("COURSE_TRANSCRIPT_DATA_DIR", "/app/data"))
JOB = DATA_DIR / "jobs" / os.environ.get("JOB_NAME", "voice_11386603-seg1")


def atomic_text(path: Path, text: str) -> None:
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(text, encoding="utf-8")
    temporary.replace(path)


def atomic_bytes(path: Path, value: bytes) -> None:
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_bytes(value)
    temporary.replace(path)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def timestamp(value: int, separator: str = ",") -> str:
    hours, value = divmod(max(0, value), 3_600_000)
    minutes, value = divmod(value, 60_000)
    seconds, milliseconds = divmod(value, 1_000)
    return f"{hours:02}:{minutes:02}:{seconds:02}{separator}{milliseconds:03}"


def ass_time(value: int) -> str:
    hours, value = divmod(max(0, value), 3_600_000)
    minutes, value = divmod(value, 60_000)
    seconds, milliseconds = divmod(value, 1_000)
    return f"{hours}:{minutes:02}:{seconds:02}.{milliseconds // 10:02}"


def ass_text(value: str) -> str:
    return (
        value.replace("\\", "\\\\")
        .replace("{", "\\{")
        .replace("}", "\\}")
        .replace("\n", "\\N")
    )


def _write_docx(path: Path, segments: list[dict[str, Any]]) -> None:
    document = Document()
    document.add_heading("Course Transcript", level=0)
    for segment in segments:
        paragraph = document.add_paragraph()
        paragraph.add_run(f"[{timestamp(int(segment['start_ms']), ':')[:-4]}] ").bold = True
        paragraph.add_run(str(segment["corrected_text"]))
    temporary = path.with_suffix(path.suffix + ".tmp")
    document.save(temporary)
    temporary.replace(path)


def _write_pdf(path: Path, segments: list[dict[str, Any]]) -> None:
    pdfmetrics.registerFont(UnicodeCIDFont("STSong-Light"))
    temporary = path.with_suffix(path.suffix + ".tmp")
    styles = getSampleStyleSheet()
    styles["Title"].fontName = "STSong-Light"
    styles["BodyText"].fontName = "STSong-Light"
    story = [Paragraph("Course Transcript", styles["Title"]), Spacer(1, 12)]
    for segment in segments:
        story.append(Paragraph(str(segment["corrected_text"]), styles["BodyText"]))
        story.append(Spacer(1, 5))
    SimpleDocTemplate(str(temporary)).build(story)
    temporary.replace(path)


def _write_ass(path: Path, segments: list[dict[str, Any]], text_key: str) -> None:
    header = """[Script Info]
Title: Course Transcript MVP export
ScriptType: v4.00+
Collisions: Normal
PlayResX: 1920
PlayResY: 1080

[V4+ Styles]
Format: Name,Fontname,Fontsize,PrimaryColour,SecondaryColour,OutlineColour,BackColour,Bold,Italic,Underline,StrikeOut,ScaleX,ScaleY,Spacing,Angle,BorderStyle,Outline,Shadow,Alignment,MarginL,MarginR,MarginV,Encoding
Style: Default,Noto Sans CJK TC,48,&H00FFFFFF,&H000000FF,&H00101010,&H80000000,0,0,0,0,100,100,0,0,1,2,1,2,80,80,60,1

[Events]
Format: Layer,Start,End,Style,Name,MarginL,MarginR,MarginV,Effect,Text
"""
    lines = [header.rstrip("\n")]
    for segment in segments:
        lines.append(
            "Dialogue: 0,"
            f"{ass_time(int(segment['start_ms']))},"
            f"{ass_time(int(segment['end_ms']))},"
            "Default,,0,0,0,,"
            f"{ass_text(str(segment[text_key]))}"
        )
    atomic_text(path, "\n".join(lines) + "\n")


def _selected_formats() -> list[str]:
    value = os.environ.get("OUTPUT_FORMATS_JSON", '["srt","txt"]')
    try:
        parsed = json.loads(value)
    except json.JSONDecodeError as exc:
        raise RuntimeError("OUTPUT_FORMATS_JSON is invalid") from exc
    if not isinstance(parsed, list):
        raise RuntimeError("OUTPUT_FORMATS_JSON must be a list")
    return normalize_output_formats(parsed)


def _artifact(path: Path, *, public: bool, output_format: str | None = None) -> dict[str, Any]:
    if not path.is_file() or path.stat().st_size <= 0:
        raise RuntimeError(f"missing or empty export: {path.name}")
    with path.open("rb") as stream:
        while stream.read(1024 * 1024):
            pass
    return {
        "name": path.name,
        "size_bytes": path.stat().st_size,
        "sha256": sha256(path),
        "source": "immutable Chirp segments with optional Gemini text correction",
        "public": public,
        "output_format": output_format,
    }


def main() -> int:
    legacy_direct_invocation = "OUTPUT_FORMATS_JSON" not in os.environ
    selected = _selected_formats()
    raw_payload = json.loads((JOB / "subtitles.json").read_text(encoding="utf-8"))
    corrected_path = JOB / "subtitles-corrected.json"
    corrected_payload = (
        json.loads(corrected_path.read_text(encoding="utf-8"))
        if corrected_path.exists()
        else None
    )
    raw_segments = raw_payload["segments"]
    corrected_by_id = (
        {str(item["segment_id"]): item for item in corrected_payload["segments"]}
        if corrected_payload
        else {}
    )
    published_segments: list[dict[str, Any]] = []
    for segment in raw_segments:
        correction = corrected_by_id.get(str(segment["segment_id"]), {})
        published_segments.append(
            {
                **segment,
                "corrected_text": correction.get("corrected_text", segment["raw_text"]),
                "uncertain_terms": correction.get("uncertain_terms", []),
            }
        )

    transcript_json = {
        "job_id": JOB.name,
        "source_timing": "chirp_3 word timestamps",
        "correction_model": corrected_payload.get("model") if corrected_payload else None,
        "segments": published_segments,
    }
    atomic_text(
        JOB / "transcript.json",
        json.dumps(transcript_json, ensure_ascii=False, indent=2) + "\n",
    )
    internal_csv = JOB / "transcript-segments.csv"
    with internal_csv.open("w", encoding="utf-8", newline="") as stream:
        writer = csv.DictWriter(
            stream,
            fieldnames=[
                "segment_id",
                "start_ms",
                "end_ms",
                "raw_text",
                "corrected_text",
                "uncertain_terms",
            ],
        )
        writer.writeheader()
        for segment in published_segments:
            writer.writerow(
                {
                    "segment_id": segment["segment_id"],
                    "start_ms": segment["start_ms"],
                    "end_ms": segment["end_ms"],
                    "raw_text": segment["raw_text"],
                    "corrected_text": segment["corrected_text"],
                    "uncertain_terms": " | ".join(segment["uncertain_terms"]),
                }
            )

    atomic_text(
        JOB / "glossary_decisions.yaml",
        json.dumps(
            {"scope": "session", "decisions": [], "source": "optional_post_edit"},
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
    )
    join_path = JOB / "join-qa.json"
    if join_path.exists():
        atomic_bytes(JOB / "join_qa.json", join_path.read_bytes())
    glossary_source = JOB / "glossary" / "global-terms.csv"
    if glossary_source.exists():
        atomic_bytes(JOB / "glossary_candidates.csv", glossary_source.read_bytes())
    else:
        atomic_text(JOB / "glossary_candidates.csv", "canonical,variants,confidence\n")

    source_srt = (
        JOB / "subtitles-corrected.srt"
        if (JOB / "subtitles-corrected.srt").exists()
        else JOB / "subtitles.srt"
    )
    source_vtt = (
        JOB / "subtitles-corrected.vtt"
        if (JOB / "subtitles-corrected.vtt").exists()
        else JOB / "subtitles.vtt"
    )
    source_txt = (
        JOB / "transcript-corrected.txt"
        if (JOB / "transcript-corrected.txt").exists()
        else JOB / "transcript-raw.txt"
    )

    public_paths: dict[str, Path] = {}
    if "srt" in selected:
        target = JOB / "transcript.srt"
        atomic_bytes(target, source_srt.read_bytes())
        public_paths["srt"] = target
    if "txt" in selected:
        target = JOB / "transcript_corrected.txt"
        atomic_bytes(target, source_txt.read_bytes())
        public_paths["txt"] = target
    if "vtt" in selected:
        target = JOB / "transcript.vtt"
        atomic_bytes(target, source_vtt.read_bytes())
        public_paths["vtt"] = target
    if "ass" in selected:
        target = JOB / "subtitles-corrected.ass"
        _write_ass(target, published_segments, "corrected_text")
        public_paths["ass"] = target
    if "csv" in selected:
        target = JOB / "transcript.csv"
        atomic_bytes(target, internal_csv.read_bytes())
        public_paths["csv"] = target

    legacy_paths: list[Path] = []
    if legacy_direct_invocation:
        atomic_bytes(JOB / "transcript_raw.txt", (JOB / "transcript-raw.txt").read_bytes())
        atomic_bytes(JOB / "transcript_timestamped.txt", (JOB / "transcript-timestamped.txt").read_bytes())
        if not (JOB / "transcript_corrected.txt").exists():
            atomic_bytes(JOB / "transcript_corrected.txt", source_txt.read_bytes())
        if not (JOB / "transcript.srt").exists():
            atomic_bytes(JOB / "transcript.srt", source_srt.read_bytes())
        if not (JOB / "transcript.vtt").exists():
            atomic_bytes(JOB / "transcript.vtt", source_vtt.read_bytes())
        if not (JOB / "transcript.csv").exists():
            atomic_bytes(JOB / "transcript.csv", internal_csv.read_bytes())
        _write_docx(JOB / "transcript.docx", published_segments)
        _write_pdf(JOB / "transcript.pdf", published_segments)
        legacy_paths = [
            JOB / "transcript_raw.txt", JOB / "transcript_corrected.txt",
            JOB / "transcript_timestamped.txt", JOB / "transcript.srt",
            JOB / "transcript.vtt", JOB / "transcript.csv",
            JOB / "transcript.docx", JOB / "transcript.pdf",
        ]

    internal_paths = [
        JOB / "transcript.json",
        internal_csv,
        JOB / "glossary_candidates.csv",
        JOB / "glossary_decisions.yaml",
        JOB / "join_qa.json",
    ]
    artifacts = [_artifact(path, public=False) for path in internal_paths]
    artifacts.extend(_artifact(path, public=False) for path in legacy_paths)
    artifacts.extend(
        _artifact(path, public=True, output_format=output_format)
        for output_format, path in public_paths.items()
    )
    manifest = {
        "scope": "selected_sidecars_plus_internal_evidence",
        "drive_upload_started": False,
        "source_timing": "chirp_3 word timestamps",
        "correction_model": corrected_payload.get("model") if corrected_payload else None,
        "selected_output_formats": selected,
        "artifacts": artifacts,
    }
    atomic_text(
        JOB / "export-manifest.json",
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
    )
    print(
        f"EXPORT=PASS segments={len(raw_segments)} corrected={bool(corrected_payload)} "
        f"selected={','.join(selected)} artifacts={len(artifacts)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
