"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import styles from "./learning-admin.module.css";

type VideoRow={youtube_video_id:string;title:string;duration_ms:number|null;latest_version_id:string|null;latest_version_number:number|null;latest_source_sha256:string|null;learning_source_version_id:string|null;learning_source_version_number:number|null;learning_source_sha256:string|null;learning_source_approved_at:string|null;learning_source_is_latest:boolean;artifact_id:string|null;artifact_source_sha256:string|null;artifact_generated_at:string|null;artifact_model:string|null;artifact_prompt_version:string|null;artifact_stale:boolean|null};
type Job={id:string;youtube_video_id:string;video_title:string;subtitle_version_id:string;artifact_type:string;prompt_version:string;model:string;status:"running"|"completed"|"failed";actor:string;error:string|null;started_at:string;finished_at:string|null};
type Overview={videos:VideoRow[];generation_jobs:Job[]};
type Filter="all"|"source"|"generate"|"current"|"stale";
function dateTime(value:string|null){if(!value)return"—";try{return new Intl.DateTimeFormat("zh-TW",{month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(value))}catch{return value}}
export default function LearningAdminPage(){
 const [data,setData]=useState<Overview|null>(null);const [busy,setBusy]=useState<string|null>(null);const [message,setMessage]=useState<string|null>(null);const [error,setError]=useState<string|null>(null);const [loading,setLoading]=useState(true);const [query,setQuery]=useState("");const [filter,setFilter]=useState<Filter>("all");
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const r=await fetch("/api/v1/review-admin/learning/overview",{cache:"no-store",credentials:"same-origin"});if(!r.ok){const b=await r.json().catch(()=>({}));throw new Error(b.detail||"目前無法讀取 AI 學習內容狀態")}setData(await r.json())}catch(e){setError(e instanceof Error?e.message:"載入失敗")}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const counts=useMemo(()=>{const videos=data?.videos||[];return{total:videos.length,approved:videos.filter(v=>v.learning_source_version_id&&v.learning_source_is_latest).length,current:videos.filter(v=>v.artifact_id&&!v.artifact_stale&&v.learning_source_is_latest).length,stale:videos.filter(v=>v.artifact_stale||Boolean(v.learning_source_version_id&&!v.learning_source_is_latest)).length}},[data]);
 const videos=useMemo(()=>{const keyword=query.trim().toLocaleLowerCase("zh-TW");return(data?.videos||[]).filter(video=>{if(keyword&&!video.title.toLocaleLowerCase("zh-TW").includes(keyword))return false;if(filter==="source")return!video.learning_source_version_id||!video.learning_source_is_latest;if(filter==="generate")return Boolean(video.learning_source_version_id&&video.learning_source_is_latest&&!video.artifact_id);if(filter==="current")return Boolean(video.artifact_id&&!video.artifact_stale&&video.learning_source_is_latest);if(filter==="stale")return Boolean(video.artifact_stale||video.learning_source_version_id&&!video.learning_source_is_latest);return true})},[data,filter,query]);
 async function approveSource(video:VideoRow){const sourceLabel=video.latest_version_number?`目前不可變字幕 v${video.latest_version_number}`:"目前已匯入字幕（系統會先凍結為不可變 v1 基準）";if(!window.confirm(`確定把「${video.title}」的${sourceLabel}核定為正式學習來源？\n\n只有你明確核定後，AI 才能根據這個版本產生正式筆記。字幕之後若再更新，系統會要求重新核定。`))return;setBusy(`source:${video.youtube_video_id}`);setMessage(null);setError(null);try{const r=await fetch(`/api/v1/review-admin/learning/videos/${encodeURIComponent(video.youtube_video_id)}/approve-source`,{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify({confirm:true})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.detail||"核定學習來源失敗");setMessage(`已核定「${video.title}」為正式學習來源。`);await load()}catch(e){setError(e instanceof Error?e.message:"核定失敗")}finally{setBusy(null)}}
 async function generate(video:VideoRow,force:boolean){const sourceVersion=video.learning_source_version_number;if(!sourceVersion||!video.learning_source_is_latest){setError("請先核定目前最新字幕版本為正式學習來源。");return}const action=force?"重新產生":"產生";const forceNotice=force?"\n這會再次呼叫模型，並以新結果更新目前這份學習整理。":"";if(!window.confirm(`${action}「${video.title}」的 AI 學習整理？\n\n來源：已核定字幕 v${sourceVersion}\n這會呼叫付費 LLM，但不會修改 YouTube。${forceNotice}\n\n若畫面中斷，請先重新整理確認狀態，不要直接重複送出。`))return;setBusy(`generate:${video.youtube_video_id}`);setMessage(`正在${action}「${video.title}」的 AI 學習整理，請勿重複操作…`);setError(null);try{const r=await fetch(`/api/v1/review-admin/learning/videos/${encodeURIComponent(video.youtube_video_id)}/generate`,{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify({confirm:true,force})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.detail||"AI 學習整理失敗");setMessage(b.generated?`「${video.title}」的 AI 學習整理已完成。`:`「${video.title}」已有目前正式來源的最新學習整理，未重複呼叫模型。`);await load()}catch(e){setError(e instanceof Error?e.message:"AI 學習整理失敗");setMessage("操作結果不明或失敗時，已重新讀取目前狀態；請先確認產生紀錄，再決定是否重試。");await load()}finally{setBusy(null)}}
 return <main className={styles.page}><div className={styles.shell}>
  <header className={styles.header}><div><p className={styles.eyebrow}>AI Learning Content</p><h1>AI 學習內容管理</h1><p>先由管理員把「大家已完成辨識／校訂」的字幕核定為正式學習來源，再讓 LLM 整理。若這支影片尚未建立版本，第一次核定會先把匯入原文凍結成不可變 v1。每份筆記都保留來源版本、SHA 與影片時間碼。</p></div><a href="/review/learn" style={{color:"#315c4b",fontWeight:800,textDecoration:"none"}}>查看學習平台 ↗</a></header>
  <div className={styles.note}>正式流程：字幕共修／辨識確認完成 → <strong>核定為學習來源</strong>（必要時自動凍結 v1）→ 產生 AI Study Pack。若之後字幕又有新版，舊筆記仍可追溯，但會標示需要重新核定／整理。學員閱讀永遠不會自動觸發付費模型，也不會修改 YouTube。</div>
  {message?<div aria-live="polite" className={styles.message} role="status">{message}</div>:null}{error?<div className={styles.error} role="alert">{error} <button onClick={()=>void load()} type="button">重新整理狀態</button></div>:null}
  {data?<><section className={styles.summary}><div><strong>{counts.total}</strong><span>課程</span></div><div><strong>{counts.approved}</strong><span>最新字幕已核定</span></div><div><strong>{counts.current}</strong><span>AI 內容最新</span></div><div><strong>{counts.stale}</strong><span>待更新／重核</span></div></section>
    <section className={styles.panel}><div className={styles.panelHeader}><div><h2>課程 AI 學習整理</h2><p>一組 Study Pack 同時提供詳細筆記、10/3 分鐘複習、重點、問答、Flashcards、測驗與名詞表。</p></div></div>
      <div className={styles.actions} style={{marginBottom:16}}><input aria-label="搜尋課程" onChange={event=>setQuery(event.target.value)} placeholder="搜尋課程名稱…" style={{minHeight:40,minWidth:240,border:"1px solid #d3dcd5",borderRadius:11,padding:"8px 11px"}} type="search" value={query}/>{([['all','全部'],['source','待核定來源'],['generate','待產生 AI'],['current','AI 最新'],['stale','待更新']] as Array<[Filter,string]>).map(([key,label])=><button aria-pressed={filter===key} className={filter===key?styles.primary:""} key={key} onClick={()=>setFilter(key)} type="button">{label}</button>)}</div>
      {videos.length?<div className={styles.grid}>{videos.map(video=>{const sourceReady=Boolean(video.learning_source_version_id&&video.learning_source_is_latest);return <article className={styles.videoCard} key={video.youtube_video_id}><h3>{video.title}</h3><div className={styles.meta}>
        <span className={styles.badge}>{video.latest_version_number?`最新字幕 v${video.latest_version_number}`:"尚未凍結字幕版本"}</span>
        {!video.learning_source_version_id?<span className={`${styles.badge} ${styles.missing}`}>尚未核定學習來源</span>:video.learning_source_is_latest?<span className={`${styles.badge} ${styles.good}`}>正式來源 v{video.learning_source_version_number}</span>:<span className={`${styles.badge} ${styles.warn}`}>正式來源仍是 v{video.learning_source_version_number}</span>}
        {!video.artifact_id?<span className={`${styles.badge} ${styles.missing}`}>尚無 AI 整理</span>:video.artifact_stale?<span className={`${styles.badge} ${styles.warn}`}>AI 整理需要更新</span>:<span className={`${styles.badge} ${styles.good}`}>AI 整理最新</span>}
        {video.artifact_model?<span className={styles.badge}>{video.artifact_model}</span>:null}
      </div>{video.learning_source_approved_at?<p style={{fontSize:12,color:"#758178"}}>正式來源核定：{dateTime(video.learning_source_approved_at)}</p>:null}{video.artifact_generated_at?<p style={{fontSize:12,color:"#758178"}}>最近整理：{dateTime(video.artifact_generated_at)}・{video.artifact_prompt_version}</p>:null}
      <div className={styles.actions}>{!sourceReady?<button disabled={busy!==null} onClick={()=>void approveSource(video)} type="button">{busy===`source:${video.youtube_video_id}`?"核定中…":video.latest_version_number?video.learning_source_version_id?`重新核定 v${video.latest_version_number}`:`核定 v${video.latest_version_number} 為學習版`:"凍結目前字幕並核定為學習版"}</button>:null}<button className={styles.primary} disabled={busy!==null||!sourceReady} onClick={()=>void generate(video,Boolean(video.artifact_id))} type="button">{busy===`generate:${video.youtube_video_id}`?"整理中…":video.artifact_id?"重新產生 AI 整理":"產生 AI 學習整理"}</button>{video.artifact_id?<a href={`/review/learn/${video.youtube_video_id}?tab=notes`}>預覽學員畫面</a>:null}</div></article>})}</div>:<div className={styles.state}>{query.trim()?`找不到包含「${query.trim()}」且符合目前篩選條件的課程。`:"目前沒有符合這個狀態的課程。"}</div>}
    </section>
    <section className={styles.panel}><div className={styles.panelHeader}><div><h2>最近產生紀錄</h2><p>若請求中斷，先看這裡是否已完成；失敗不會影響正式字幕，也不會被誤標成成功。</p></div></div><div className={styles.jobs}>{data.generation_jobs.length?data.generation_jobs.map(job=><div className={styles.job} key={job.id}><div><strong>{job.video_title}</strong><p>{job.model}・開始 {dateTime(job.started_at)}{job.error?`・${job.error}`:""}</p></div><span className={`${styles.status} ${styles[job.status]}`}>{job.status==="completed"?"完成":job.status==="running"?"處理中":"失敗"}</span></div>):<div className={styles.state}>還沒有 AI 學習內容產生紀錄。</div>}</div></section>
  </>:loading?<div className={styles.state}>正在讀取 AI 學習內容狀態…</div>:<div className={styles.state}>目前沒有可顯示的資料。<button onClick={()=>void load()} type="button">重新載入</button></div>}
 </div></main>
}
