"""Requested user-facing export formats, separate from internal evidence."""
from __future__ import annotations

from collections.abc import Iterable
import os


DEFAULT_OUTPUT_FORMATS = ("srt", "txt", "csv")
ALLOWED_OUTPUT_FORMATS = frozenset(
    {"srt", "txt", "csv", "vtt", "ass", "docx", "pdf"}
)
PRODUCTION_OUTPUT_FORMATS = frozenset({"srt", "txt", "csv", "vtt", "ass"})
DEPRECATED_DOCUMENT_FORMATS = frozenset({"docx", "pdf"})


def normalize_output_formats(formats: Iterable[object] | None) -> list[str]:
    """Validate and de-duplicate the user-visible export selection."""
    if formats is None:
        return list(DEFAULT_OUTPUT_FORMATS)
    normalized: list[str] = []
    production_execution = os.environ.get("OUTPUT_FORMATS_JSON") is not None
    for value in formats:
        if not isinstance(value, str) or value not in ALLOWED_OUTPUT_FORMATS:
            raise ValueError("Unsupported output format")
        if production_execution and value in DEPRECATED_DOCUMENT_FORMATS:
            continue
        if value not in normalized:
            normalized.append(value)
    if not normalized:
        raise ValueError("At least one output format is required")
    return normalized


def production_output_formats(formats: Iterable[object] | None) -> list[str]:
    """Return formats the production pipeline is allowed to materialize.

    DOCX/PDF remain accepted at the API boundary for old clients and stored job
    records, but are intentionally not generated by the production pipeline.
    """
    selected = [
        value
        for value in normalize_output_formats(formats)
        if value in PRODUCTION_OUTPUT_FORMATS
    ]
    if not selected:
        raise ValueError("At least one non-document output format is required")
    return selected
